"use client"

import { StatusBadge } from "@/components/status-badge"
import { StatusBubble } from "@/components/status-bubble"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"
import { updatePico } from "@/lib/database"
import { Pico } from "@/lib/types"
import { formatDistanceToNow } from "date-fns"
import { useRouter } from "next/navigation"
import React, { useState } from "react"
import { toast } from "sonner"
import { useDebouncedCallback } from "use-debounce"
import LiveCommandFeed from "./live-command-feed"

interface PicoCardProps {
  pico: Pico
}

export default function PicoCard({ pico }: PicoCardProps) {
  const [sheetOpen, setSheetOpen] = useState(false)
  const [dialogOpen, setDialogOpen] = useState(false)
  const [name, setName] = useState(pico.name || "")
  const router = useRouter()

  const handleSave = async () => {
    try {
      await updatePico(pico.id, { name: name.trim() || undefined })
      toast.success("Pico name updated")

      // Refresh the page data to get updated pico list
      router.refresh()
    } catch {
      toast.error("Failed to update pico name")
      // Revert the name on error
      setName(pico.name || "")
    }
  }

  const handleEdit = useDebouncedCallback((value: string) => {
    if (value.trim() !== (pico.name || "")) {
      handleSave()
    }
  }, 500)

  const handleCardClick = () => {
    setSheetOpen(true)
  }

  const handleLiveClick = (e: React.MouseEvent) => {
    e.stopPropagation()
    setDialogOpen(true)
  }

  return (
    <>
      <Card
        onClick={handleCardClick}
        key={pico.id}
        className="relative transition-shadow hover:shadow-lg hover:shadow-foreground"
      >
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <StatusBubble status={pico.status} />
              <div>
                <CardTitle className="text-lg">
                  {pico.name ? pico.name : `Pico ${pico.id}`}
                </CardTitle>
                <CardDescription className="flex items-center gap-2">
                  {pico.macAddress.toUpperCase()}
                </CardDescription>
              </div>
            </div>
            <div className="flex flex-col items-end gap-1">
              <StatusBadge status={pico.status} />
            </div>
          </div>
        </CardHeader>
        <CardContent className="flex">
          <Button className="flex-1" onClick={(e) => handleLiveClick(e)} variant={"outline"}>
            Show Live Feed
          </Button>
        </CardContent>
      </Card>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Live Feed for {pico.id}</DialogTitle>
            <DialogDescription>
              A real-time feed of the commands generated by block placements on this Pico. This view
              is read-only.
            </DialogDescription>
          </DialogHeader>
          <LiveCommandFeed macAddress={pico.macAddress} />
        </DialogContent>
      </Dialog>

      <Sheet open={sheetOpen} onOpenChange={setSheetOpen}>
        {/* Edit Sheet */}
        <SheetContent>
          <SheetHeader>
            <SheetTitle>Pico Details</SheetTitle>
            <SheetDescription>View and edit pico information</SheetDescription>
          </SheetHeader>

          {/* <div className="space-y-6 py-6"> */}
          <div className="grid flex-1 auto-rows-min gap-6 px-4">
            {/* Status - Read Only */}
            <div className="grid gap-3">
              <Label>Status</Label>
              <div className="flex items-center gap-2">
                <StatusBubble status={pico.status} />
                <StatusBadge status={pico.status} />
              </div>
            </div>

            {/* Pico ID - Read Only */}
            <div className="grid gap-3">
              <Label>Pico ID</Label>
              <Input disabled value={pico.id} />
            </div>

            {/* Pico Name - Editable */}
            <div className="grid gap-3">
              <Label htmlFor="pico-name">Pico Name</Label>
              <Input
                id="pico-name"
                value={name}
                placeholder={`Unnamed Pico ${pico.id}`}
                onChange={(e) => {
                  setName(e.target.value)
                  handleEdit(e.target.value)
                }}
              />
            </div>

            {/* MAC Address - Read Only */}
            <div className="grid gap-3">
              <Label>MAC Address</Label>
              <Input disabled className="font-mono" value={pico.macAddress.toUpperCase()} />
            </div>

            {/* Last Seen - Read Only */}
            <div className="grid gap-3">
              <Label>Last Seen</Label>
              <Tooltip>
                <TooltipTrigger>
                  <Input disabled value={pico.lastSeen.toLocaleString("en-UK")} />
                </TooltipTrigger>
                <TooltipContent side="left">
                  <p>{formatDistanceToNow(pico.lastSeen, { addSuffix: true })}</p>
                </TooltipContent>
              </Tooltip>
            </div>

            {/* Assignments Count - Read Only */}
            <div className="space-y-2">
              <Label>Active Assignments</Label>
              <Input
                disabled
                value={`${pico.assignments?.filter((a) => a.isActive).length || 0} assignment(s)`}
              />
            </div>
          </div>
        </SheetContent>
      </Sheet>
    </>
  )
}
