import Sidebar from "@/components/sidebar"
import type { Metadata } from "next"
import { ThemeProvider } from "next-themes"
import localFont from "next/font/local"
import { Toaster } from "sonner"
import "./globals.css"

const geistSans = localFont({
  src: [
    {
      path: "../public/fonts/Geist[wght].woff2",
      style: "normal",
    },
    {
      path: "../public/fonts/Geist-Italic[wght].woff2",
      style: "italic",
    },
  ],
  variable: "--font-geist-sans",
})

const geistMono = localFont({
  src: [
    {
      path: "../public/fonts/GeistMono[wght].woff2",
      style: "normal",
    },
    {
      path: "../public/fonts/GeistMono-Italic[wght].woff2",
      style: "italic",
    },
  ],
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Sidebar>
            {children}
            <Toaster />
          </Sidebar>
        </ThemeProvider>
      </body>
    </html>
  )
}
