import Sidebar from "@/components/sidebar"
import type { Metadata } from "next"
import { ThemeProvider } from "next-themes"
import { Geist, Geist_Mono } from "next/font/google"
import { Toaster } from "sonner"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // const [sidebarOpen, setSidebarOpen] = useState(false)
  // const pathname = usePathname()

  // const navigation = [
  //   { name: "Overview", href: "/", icon: Home },
  //   { name: "Robots", href: "/robots", icon: Bot },
  //   { name: "Picos", href: "/picos", icon: Cpu },
  //   { name: "Command Queue", href: "/commands", icon: Terminal },
  //   { name: "Settings", href: "/settings", icon: Settings },
  // ]

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <body className="antialiased"> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Sidebar>
            {children}
            <Toaster />
          </Sidebar>
        </ThemeProvider>
      </body>
    </html>
  )
}
